apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: cncamp
spec:
  acme:
    email: ryan.sun@livermap.com
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cncamp-tls
  namespace: cncamp
spec:
  issuerRef:
    name: letsencrypt-prod
  dnsNames:
    - cncamp.zzzzzsy.xyz
  secretName: cncamp-tls
