apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpclient
  namespace: cncamp
  labels:
    app: httpclient
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpclient
  template:
    metadata:
      labels:
        app: httpclient
    spec:
      containers:
        - name: app
          image: zzzzzsy/cncamp04:latest
          ports:
            - containerPort: 8080
              name: http-app
          resources:
            limits:
              memory: "200Mi"
              cpu: "100m"
            requests:
              memory: "100Mi"
              cpu: "50m"
          livenessProbe:
            httpGet:
              path: /ip
              port: 8080
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            failureThreshold: 3
            periodSeconds: 10
          volumeMounts:
            - name: httpclient-conf
              mountPath: "/usr/app/conf"
              readOnly: true
      volumes:
        - name: httpclient-conf
          configMap:
            defaultMode: 420
            name: httpclient-conf
      # imagePullSecrets:
      #   - name: dockerhub
